### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by PulsarFX** [rany2/ha-open-meteo-solar-forecast#22]
I found this in my log, after all sensors became unavailable:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.open_meteo_solar_forecast
Quelle: helpers/update_coordinator.py:315
Integration: Open-Meteo Solar Forecast (Dokumentation, Probleme)
Erstmals aufgetreten: 11. Juni 2024 um 20:01:00 (1903 Vorkommnisse)
Zuletzt protokolliert: 00:29:10

Unexpected error fetching open_meteo_solar_forecast data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/open_meteo_solar_forecast/coordinator.py", line 63, in _async_update_data
    return await self.forecast.estimate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/open_meteo_solar_forecast/open_meteo_solar_forecast.py", line 155, in estimate
    data = await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/open_meteo_solar_forecast/open_meteo_solar_forecast.py", line 122, in _request
    raise OpenMeteoSolarForecastRatelimitError("Rate limit exceeded")
open_meteo_solar_forecast.exceptions.OpenMeteoSolarForecastRatelimitError: Rate limit exceeded
```

It says it happened 1903 times. The time span is about 29 hours. This sounds like an incredible high polling rate. I have 3 entries configured.

**Comment by rany2** [comment]
Are you on the latest version?

**Comment by rany2** [comment]
Actually I don't think it's possible that you are on the latest version given when the release with the fix was made: https://github.com/rany2/ha-open-meteo-solar-forecast/releases/tag/0.1.11

**Comment by PulsarFX** [comment]
Lol, right, that is 1.10.
You are very fast. Just checked hacs yesterday.
