### ISSUE TITLE
Errors in the HA log file

### ISSUE THREAD

**Issue by alfwro13** [rany2/ha-open-meteo-solar-forecast#6]
I have noticed that there are quite a few errors thrown by this integration:

```
2024-06-08 08:23:00.542 ERROR (MainThread) [custom_components.open_meteo_solar_forecast] Unexpected error fetching open_meteo_solar_forecast data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/open_meteo_solar_forecast/coordinator.py", line 57, in _async_update_data
    return await self.forecast.estimate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/open_meteo_solar_forecast/open_meteo_solar_forecast.py", line 160, in estimate
    wind_speed * 1000 / 3600
    ~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
2024-06-08 08:23:03.186 ERROR (MainThread) [custom_components.open_meteo_solar_forecast] Unexpected error fetching open_meteo_solar_forecast data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/open_meteo_solar_forecast/coordinator.py", line 57, in _async_update_data
    return await self.forecast.estimate()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/open_meteo_solar_forecast/open_meteo_solar_forecast.py", line 160, in estimate
    wind_speed * 1000 / 3600
    ~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by rany2** [comment]
It's already fixed, update to the latest version
